### ISSUE TITLE
The Azure deployment fails with the region

### ISSUE THREAD

**Issue by steveculshaw** [MikeWasson/BookService#9]
Tried the "deploy to azure" option on the [MSDN](https://docs.microsoft.com/en-us/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-1), but get the error ... 
No registered resource provider found for location 'North Europe' and API version '2.0' for type 'servers'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview, 2015-05-01-preview'. The supported locations are 'australiaeast, australiasoutheast, etc. etc.

**Comment by VeronicaWasson** [comment]
The deployment is actually from a different repo. I opened a PR in that repo, see tfitzmac/BookService#2

**Comment by VeronicaWasson** [comment]
Should be fixed now
